version: 1
services:
  - type: web
    name: my-html-app
    env: static
    staticSite:
      publishPath: ./public  # Adjust this path to where your HTML files are located
      routes:
        - src: /.*
          dest: /index.html
